name: Build .NET MAUI Android AAB Locally

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted  # ensure your self-hosted runner is tagged properly

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust as needed

      - name: Install MAUI workload (optional if already installed)
        continue-on-error: true  # avoids breaking if it's already installed or times out
        run: dotnet workload install maui

      - name: Restore NuGet packages
        run: dotnet restore Calculex.csproj

      - name: Build .NET MAUI Android AAB
        run: dotnet publish Calculex.csproj -f net8.0-android -c Release -o ./output /p:GenerateAppBundle=true

      - name: Copy AAB to E:\MAUI_AABs\
        run: |
          if not exist "E:\MAUI_AABs" mkdir "E:\MAUI_AABs"
          copy ".\output\*.aab" "E:\MAUI_AABs\"
