name: Build .NET MAUI Android AAB

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore NuGet packages
        run: dotnet restore Calculex.csproj

      - name: Build Android AAB
        run: dotnet publish Calculex.csproj -f net8.0-android -c Release -o ./output /p:GenerateAppBundle=true

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: output/**/*.aab
